services:
   keycloak:
      image: quay.io/keycloak/keycloak:26.0
      restart: always
      environment:
        - KC_BOOTSTRAP_ADMIN_USERNAME=admin 
        - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
        - KEYCLOAK_IMPORT=/tmp/refit-realm.json
      volumes:
        - ./realms:/opt/keycloak/data/import
      ports:
        - "8070:8080"
      command: ["start-dev", "--import-realm"]
